---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  helmVersion: v3
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.7.2
  values:
    global:
      rbac:
        create: true
      imagePullSecrets:
      - name: tpcdeploybot-creds
    installCRDs: true
    # image repo details
    image:
      repository: infacloud-ct-quay.jfrog.io/jetstack/cert-manager-controller
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        labels:
          release: monitoringaddon
    serviceAccount:
      create: true
      
    webhook:
      enabled: true
      image:
        repository: infacloud-ct-quay.jfrog.io/jetstack/cert-manager-webhook
    cainjector:
      image:
        repository: infacloud-ct-quay.jfrog.io/jetstack/cert-manager-cainjector
    

